### ISSUE TITLE
Only showing stats for the first request always

### ISSUE THREAD

**Issue by akshatdev0** [shindig/insomnia-plugin-load-test-timing#1]
It only shows the stats for the first request always. No issue with the requests, manually they work fine and response comes.
If I move another request to first than it's stats will show and others will be NaN.

Please check below screenshot.
![image](https://user-images.githubusercontent.com/29691117/86212421-a02c4b00-bb95-11ea-8fa9-6bc4d675b945.png)

**Comment by shindig** [comment]
Fixed in v1.0.1
