### ISSUE TITLE
Run on Request

### ISSUE THREAD

**Issue by lukepighetti** [shindig/insomnia-plugin-load-test-timing#12]
I am using this to develop single Requests. I end up having to make a folder to put a single Request in for load testing. This is not a dealbreaker, but it would be nice if there was an option to just run on a single Request

**Comment by xlith** [comment]
We had this feature in the past. Then Insomnia changed the APIs. Let me have a look if that's still possible.

**Comment by xlith** [comment]
This should solve the issue. @shindig can you please review?
