### ISSUE TITLE
The "Successes" column show every time the count of interations

### ISSUE THREAD

**Issue by Strackie** [shindig/insomnia-plugin-load-test-timing#2]
Hi, the color is changing depend on response result. But the count in the successes column stay the same like the interations. Thus I can not see, how much requests failed. 
![perftest](https://user-images.githubusercontent.com/20201628/99061544-055f6680-25a2-11eb-9323-1586d5185b06.png)

**Comment by xlith** [comment]
Thank you. This issue is solved with this commit 900ebac8d88fc5590a4c9008a1c5dfd4e53ba084
