### ISSUE TITLE
Input dialog doesn't work

### ISSUE THREAD

**Issue by PeterKurucz** [shindig/insomnia-plugin-load-test-timing#6]
I'have updated my Insomnia to the newest release (2021.05.0) and after it's not possible to enter delay and paralell/seq in input dialog.
After entering number of iterations dialog will be closed (and maybe test will be processed)
Can you verify it?
Plugin-relese is: 1.0.2

**Comment by xlith** [comment]
I am looking into it. It seems there is a problem with Insomnia, but I need to investigate further.

**Comment by xlith** [comment]
It appears there was a problem in the Insomnia App itself and they fix it in the latest release. 
https://github.com/Kong/insomnia/pull/3962
With this PR the problem seems to be solved.
