### ISSUE TITLE
Canceling a running test

### ISSUE THREAD

**Issue by iDevelopThings** [shindig/insomnia-plugin-load-test-timing#8]
Hey - sorry I wasn't sure where to ask this;

Is there a way to cancel a running test?

I saw there's some code for handling aborts, but I couldn't figure a way to stop it. Started a test for 10,000 requests and it's taking a while 😅

Would happily submit a PR if it just needs a button or something adding to the progress modal

Thanks for making a sweet plugin though 👍

**Comment by iDevelopThings** [comment]
To add to this - I saw there's a commit already for something related... am I being dumb/could it be my theme? 🤔

![image](https://user-images.githubusercontent.com/4105581/148080850-51eb5888-5601-480a-bf00-bbf15a047ec1.png)

**Comment by shindig** [comment]
Fixed now in 1.0.5 (can close the progress bar window, which will abort/cancel the running tests).
